parameters:
   - name: azureServiceConnection
     type: string
   - name: resourceGroupName
     type: string
   - name: template
     type: string
   - name: location
     type: string
   - name: virtualNetworkName
     type: string
   - name: virtualNetworkAddressPrefixes
     type: string
   - name: subnets
     type: string
   - name: logAnalyticsWorkspaceName
     type: string
   - name: subscriptionId
     type: string
steps:
- task: AzureCLI@2
  displayName: Upsert VNet ${{parameters.virtualNetworkName}} 
  inputs:
    azureSubscription: ${{parameters.azureServiceConnection}} 
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: | 
                     az deployment group create --resource-group ${{parameters.resourceGroupName}} `
                              --template-file '$(Build.SourcesDirectory)/${{parameters.template }}' `
                              --parameters `
                                 location='${{parameters.location}}' `
                                 virtualNetworkName='${{parameters.virtualNetworkName}}' `
                                 virtualNetworkAddressPrefixes="${{parameters.virtualNetworkAddressPrefixes}}" `
                                 subnets='${{parameters.subnets}}' `
                                 logAnalyticsWorkspaceResourceId='/subscriptions/${{parameters.subscriptionId}}/resourceGroups/${{parameters.resourceGroupName}}/providers/Microsoft.OperationalInsights/workspaces/${{parameters.logAnalyticsWorkspaceName}}'


